NAME, all, clean, fclean, re

mon makefile doit creer libftprintf.a

# include <stdarg.h> 
# include <stdio.h>
# include <unistd.h>
# include <stdlib.h>

# include "is_char.c"
# include "is_num.c"
//#include "libft.c"
